LABEL_MAP = {
    0: "Entailment",
    1: "Neutral",
    2: "Contradiction"
}

# For specific keywords that often get mistranslated
HARDCODE_TRANSLATIONS = {
    "sé": "know", #sé often gets reverse-translated as "HE"
    "sé.": "know",
    "sé,": "know"
}

# Models that have been tested and verified to work with this tool
# Info on GPT models: https://platform.openai.com/docs/models
# Info on LLAMA models: https://docs.llama-api.com/quickstart
SUPPORTED_LLM_MODELS = {
    "gpt": [
        "o1-preview",
        "o1-mini",
        "gpt-4o",
        "gpt-4o-2024-08-06",
        "gpt-4o-2024-05-13",
        "gpt-4o-mini",
        "gpt-4o-mini-2024-07-18",
        "gpt-4-turbo",
        "gpt-4-turbo-preview",
        "gpt-4-0125-preview",
        "gpt-4-1106-preview",
        "gpt-4",
        "gpt-4-0613",
        "gpt-3.5-turbo",
        "gpt-3.5-turbo-1106",
        "gpt-3.5-turbo-0125"
    ],
    "llama": [
        "llama3.2-11b-vision",
        "llama3.2-1b",
        "llama3.2-3b",
        "llama3.2-90b",
        "llama3.1-405b",
        "llama3.1-70b",
        "llama3.1-8b",
        "llama3-70b",
        "llama3-8b",
        "gemma2-27b",
        "gemma2-9b",
        "mixtral-8x22b-instruct",
        "mixtral-8x7b-instruct",
        "mistral-7b-instruct",
        "llama2-13b", 
        "llama2-70b",
        "llama2-7b",
        "Nous-Hermes-2-Mixtral-8x7B-DPO",
    ]
}

LANGUAGE_CODES = {
    'afrikaans': 'af',
    'albanian': 'sq',
    'amharic': 'am',
    'arabic': 'ar',
    'armenian': 'hy',
    'assamese': 'as',
    'aymara': 'ay',
    'azerbaijani': 'az',
    'bambara': 'bm',
    'basque': 'eu',
    'belarusian': 'be',
    'bengali': 'bn',
    'bhojpuri': 'bho',
    'bosnian': 'bs',
    'bulgarian': 'bg',
    'catalan': 'ca',
    'cebuano': 'ceb',
    'chichewa': 'ny',
    'chinese': 'zh-CN', # (simplified)
    'chinese (traditional)': 'zh-TW',
    'corsican': 'co',
    'croatian': 'hr',
    'czech': 'cs',
    'danish': 'da',
    'dhivehi': 'dv',
    'dogri': 'doi',
    'dutch': 'nl',
    'english': 'en',
    'esperanto': 'eo',
    'estonian': 'et',
    'ewe': 'ee',
    'filipino': 'tl',
    'finnish': 'fi',
    'french': 'fr',
    'frisian': 'fy',
    'galician': 'gl',
    'georgian': 'ka',
    'german': 'de',
    'greek': 'el',
    'guarani': 'gn',
    'gujarati': 'gu',
    'haitian creole': 'ht',
    'hausa': 'ha',
    'hawaiian': 'haw',
    'hebrew': 'iw',
    'hindi': 'hi',
    'hmong': 'hmn',
    'hungarian': 'hu',
    'icelandic': 'is',
    'igbo': 'ig',
    'ilocano': 'ilo',
    'indonesian': 'id',
    'irish': 'ga',
    'italian': 'it',
    'japanese': 'ja',
    'javanese': 'jw',
    'kannada': 'kn',
    'kazakh': 'kk',
    'khmer': 'km',
    'kinyarwanda': 'rw',
    'konkani': 'gom',
    'korean': 'ko',
    'krio': 'kri',
    'kurdish (kurmanji)': 'ku',
    'kurdish (sorani)': 'ckb',
    'kyrgyz': 'ky',
    'lao': 'lo',
    'latin': 'la',
    'latvian': 'lv',
    'lingala': 'ln',
    'lithuanian': 'lt',
    'luganda': 'lg',
    'luxembourgish': 'lb',
    'macedonian': 'mk',
    'maithili': 'mai',
    'malagasy': 'mg',
    'malay': 'ms',
    'malayalam': 'ml',
    'maltese': 'mt',
    'maori': 'mi',
    'marathi': 'mr',
    'meiteilon (manipuri)': 'mni-Mtei',
    'mizo': 'lus',
    'mongolian': 'mn',
    'myanmar': 'my',
    'nepali': 'ne',
    'norwegian': 'no',
    'odia (oriya)': 'or',
    'oromo': 'om',
    'pashto': 'ps',
    'persian': 'fa',
    'polish': 'pl',
    'portuguese': 'pt',
    'punjabi': 'pa',
    'quechua': 'qu',
    'romanian': 'ro',
    'russian': 'ru',
    'samoan': 'sm',
    'sanskrit': 'sa',
    'scots gaelic': 'gd',
    'sepedi': 'nso',
    'serbian': 'sr',
    'sesotho': 'st',
    'shona': 'sn',
    'sindhi': 'sd',
    'sinhala': 'si',
    'slovak': 'sk',
    'slovenian': 'sl',
    'somali': 'so',
    'spanish': 'es',
    'sundanese': 'su',
    'swahili': 'sw',
    'swedish': 'sv',
    'tajik': 'tg',
    'tamil': 'ta',
    'tatar': 'tt',
    'telugu': 'te',
    'thai': 'th',
    'tigrinya': 'ti',
    'tsonga': 'ts',
    'turkish': 'tr',
    'turkmen': 'tk',
    'twi': 'ak',
    'ukrainian': 'uk',
    'urdu': 'ur',
    'uyghur': 'ug',
    'uzbek': 'uz',
    'vietnamese': 'vi',
    'welsh': 'cy',
    'xhosa': 'xh',
    'yiddish': 'yi',
    'yoruba': 'yo',
    'zulu': 'zu'
}

PROMPT_COMPONENTS = {
    'afrikaans': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'albanian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'amharic': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'arabic': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'armenian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'assamese': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'aymara': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'azerbaijani': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'bambara': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'basque': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'belarusian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'bengali': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'bhojpuri': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'bosnian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'bulgarian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'catalan': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'cebuano': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'chichewa': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'chinese': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'chinese (traditional)': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'corsican': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'croatian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'czech': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'danish': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'dhivehi': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'dogri': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'dutch': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'english': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'esperanto': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'estonian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'ewe': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'filipino': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'finnish': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'french': {"Premise": "Premise", "Hypothesis": "Hypothèse", "Label": "Étiquette"},
    'frisian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'galician': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'georgian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'german': {"Premise": "Prämisse", "Hypothesis": "Hypothese", "Label": "Etikett"},
    'greek': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'guarani': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'gujarati': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'haitian creole': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'hausa': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'hawaiian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'hebrew': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'hindi': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'hmong': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'hungarian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'icelandic': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'igbo': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'ilocano': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'indonesian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'irish': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'italian': {"Premise": "Premere", "Hypothesis": "Ipotesi", "Label": "Etichetta"},
    'japanese': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'javanese': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'kannada': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'kazakh': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'khmer': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'kinyarwanda': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'konkani': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'korean': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'krio': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'kurdish (kurmanji)': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'kurdish (sorani)': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'kyrgyz': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'lao': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'latin': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'latvian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'lingala': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'lithuanian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'luganda': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'luxembourgish': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'macedonian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'maithili': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'malagasy': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'malay': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'malayalam': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'maltese': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'maori': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'marathi': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'meiteilon (manipuri)': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'mizo': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'mongolian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'myanmar': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'nepali': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'norwegian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'odia (oriya)': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'oromo': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'pashto': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'persian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'polish': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'portuguese': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'punjabi': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'quechua': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'romanian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'russian': {"Premise": "Презюмировать", "Hypothesis": "Гипотеза", "Label": "Лабель"},
    'samoan': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'sanskrit': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'scots gaelic': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'sepedi': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'serbian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'sesotho': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'shona': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'sindhi': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'sinhala': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'slovak': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'slovenian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'somali': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'spanish': {"Premise": "Premisa", "Hypothesis": "Hipótesis", "Label": "Etiqueta"},
    'sundanese': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'swahili': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'swedish': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'tajik': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'tamil': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'tatar': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'telugu': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'thai': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'tigrinya': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'tsonga': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'turkish': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'turkmen': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'twi': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'ukrainian': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'urdu': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'uyghur': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'uzbek': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'vietnamese': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'welsh': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'xhosa': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'yiddish': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'yoruba': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"},
    'zulu': {"Premise": "Premise", "Hypothesis": "Hypothesis", "Label": "Label"}
}
